import express from "express";
import path from "path";
import nodemailer from "nodemailer";
import { createServer as createViteServer } from "vite";

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API route for handling booking and sending emails
  app.post("/api/book", async (req, res) => {
    try {
      const {
        fullName,
        email,
        phone,
        location,
        serviceTitle,
        preferredDate,
        preferredTime,
        insuranceProvider,
        isEmergency,
        notes,
      } = req.body;

      if (!fullName || !email || !phone) {
        return res.status(400).json({ success: false, error: "Missing required fields (Name, Email, Phone)" });
      }

      const adminEmail = process.env.ADMIN_EMAIL || "aspirantmlengineer@gmail.com";
      const referenceId = "GA-" + Math.floor(100000 + Math.random() * 900000);

      const emailHtmlAdmin = `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px; color: #0f172a; }
            .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
            .header { background: #0369a1; color: #ffffff; padding: 24px; text-align: center; }
            .content { padding: 24px; }
            .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
            .table td { padding: 12px; border-bottom: 1px solid #f1f5f9; font-size: 14px; }
            .table td.label { font-weight: bold; color: #475569; width: 40%; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-weight: bold; font-size: 12px; background: #e0f2fe; color: #0369a1; }
            .badge-emergency { background: #ffe4e6; color: #e11d48; }
            .footer { background: #f1f5f9; padding: 16px; text-align: center; font-size: 12px; color: #64748b; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h2 style="margin:0;">New Patient Appointment Request</h2>
              <p style="margin:4px 0 0; opacity:0.9; font-size:14px;">Georgia Dental Care & Cosmetics</p>
            </div>
            <div class="content">
              <p style="margin-top:0;"><strong>Reference ID:</strong> <span class="badge">${referenceId}</span> ${isEmergency ? '<span class="badge badge-emergency">⚡ URGENT SAME-DAY</span>' : ''}</p>
              
              <table class="table">
                <tr><td class="label">Patient Name</td><td>${fullName}</td></tr>
                <tr><td class="label">Patient Email</td><td><a href="mailto:${email}">${email}</a></td></tr>
                <tr><td class="label">Patient Phone</td><td><a href="tel:${phone}">${phone}</a></td></tr>
                <tr><td class="label">Requested Service</td><td><strong>${serviceTitle || 'General Dentistry'}</strong></td></tr>
                <tr><td class="label">Location</td><td>${location || 'Main Flagship Office'}</td></tr>
                <tr><td class="label">Preferred Date</td><td>${preferredDate}</td></tr>
                <tr><td class="label">Time Window</td><td>${preferredTime}</td></tr>
                <tr><td class="label">Insurance Provider</td><td>${insuranceProvider || 'Self-Pay / None'}</td></tr>
                <tr><td class="label">Notes / Anxiety Info</td><td>${notes || 'None provided'}</td></tr>
              </table>
            </div>
            <div class="footer">
              This email notification was automatically generated by Georgia Dental Booking System.
            </div>
          </div>
        </body>
        </html>
      `;

      const emailHtmlCustomer = `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px; color: #0f172a; }
            .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
            .header { background: #0284c7; color: #ffffff; padding: 28px; text-align: center; }
            .content { padding: 28px; }
            .box { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 12px; padding: 16px; margin: 20px 0; }
            .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px dashed #cbd5e1; font-size: 14px; }
            .footer { background: #f8fafc; padding: 20px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h2 style="margin:0;">Appointment Request Received!</h2>
              <p style="margin:6px 0 0; opacity:0.9; font-size:14px;">Georgia Dental Care & Cosmetics</p>
            </div>
            <div class="content">
              <p>Dear <strong>${fullName}</strong>,</p>
              <p>Thank you for scheduling with Georgia Dental Care & Cosmetics. We have received your appointment request and our concierge team is reserving your slot.</p>
              
              <div class="box">
                <div style="font-size:11px; font-weight:bold; color:#0369a1; text-transform:uppercase; margin-bottom:12px;">Booking Summary (REF #${referenceId})</div>
                <div class="row"><strong>Treatment:</strong> <span>${serviceTitle}</span></div>
                <div class="row"><strong>Date:</strong> <span>${preferredDate}</span></div>
                <div class="row"><strong>Time:</strong> <span>${preferredTime}</span></div>
                <div class="row"><strong>Location:</strong> <span>${location}</span></div>
                <div class="row"><strong>Insurance:</strong> <span>${insuranceProvider}</span></div>
              </div>

              <p style="font-size:13px; color:#475569;">Our care coordinator will review your request and call or text you shortly at <strong>${phone}</strong> to confirm final arrival details.</p>
            </div>
            <div class="footer">
              Georgia Dental Care & Cosmetics • (404) 555-0199 • 1200 Peachtree St NE, Atlanta, GA
            </div>
          </div>
        </body>
        </html>
      `;

      let mailSent = false;
      let previewUrlAdmin: string | false = false;
      let previewUrlCustomer: string | false = false;
      let smtpError = null;
      let deliveryMethod = "none";

      // 1. Try custom SMTP if configured
      if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
        try {
          const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: Number(process.env.SMTP_PORT) || 587,
            secure: Number(process.env.SMTP_PORT) === 465,
            auth: {
              user: process.env.SMTP_USER,
              pass: process.env.SMTP_PASS,
            },
          });

          await transporter.sendMail({
            from: `"Georgia Dental System" <${process.env.SMTP_USER}>`,
            to: adminEmail,
            subject: `[New Booking] ${fullName} - ${serviceTitle} (${referenceId})`,
            html: emailHtmlAdmin,
          });

          await transporter.sendMail({
            from: `"Georgia Dental Care" <${process.env.SMTP_USER}>`,
            to: email,
            subject: `Appointment Confirmation Request #${referenceId} - Georgia Dental Care`,
            html: emailHtmlCustomer,
          });

          mailSent = true;
          deliveryMethod = "smtp";
        } catch (err: any) {
          console.error("SMTP Delivery Error:", err);
          smtpError = err.message;
        }
      }

      // 2. Fallback to Ethereal Test Account if custom SMTP is not set or failed
      if (!mailSent) {
        try {
          const testAccount = await nodemailer.createTestAccount();
          const testTransporter = nodemailer.createTransport({
            host: "smtp.ethereal.email",
            port: 587,
            secure: false,
            auth: {
              user: testAccount.user,
              pass: testAccount.pass,
            },
          });

          const infoAdmin = await testTransporter.sendMail({
            from: `"Georgia Dental Booking" <no-reply@georgiadental.com>`,
            to: adminEmail,
            subject: `[New Booking] ${fullName} - ${serviceTitle} (${referenceId})`,
            html: emailHtmlAdmin,
          });

          const infoCustomer = await testTransporter.sendMail({
            from: `"Georgia Dental Care" <no-reply@georgiadental.com>`,
            to: email,
            subject: `Appointment Confirmation Request #${referenceId} - Georgia Dental Care`,
            html: emailHtmlCustomer,
          });

          mailSent = true;
          deliveryMethod = "ethereal_test_server";
          previewUrlAdmin = nodemailer.getTestMessageUrl(infoAdmin);
          previewUrlCustomer = nodemailer.getTestMessageUrl(infoCustomer);
        } catch (etherealErr: any) {
          console.error("Ethereal Fallback Error:", etherealErr);
          smtpError = etherealErr.message;
        }
      }

      console.log(`[BOOKING DISPATCH] ID: ${referenceId} | Method: ${deliveryMethod}`);
      console.log(` -> Admin Recipient: ${adminEmail}`);
      console.log(` -> Customer Recipient: ${email}`);
      if (previewUrlAdmin) console.log(` -> Admin Email Preview: ${previewUrlAdmin}`);
      if (previewUrlCustomer) console.log(` -> Customer Email Preview: ${previewUrlCustomer}`);

      return res.json({
        success: true,
        referenceId,
        mailSent,
        deliveryMethod,
        adminEmailSentTo: adminEmail,
        customerEmailSentTo: email,
        previewUrlAdmin,
        previewUrlCustomer,
        smtpError,
        bookingDetails: {
          referenceId,
          fullName,
          email,
          phone,
          location,
          serviceTitle,
          preferredDate,
          preferredTime,
          insuranceProvider,
          isEmergency,
          notes,
          timestamp: new Date().toISOString(),
        }
      });
    } catch (error: any) {
      console.error("Booking Endpoint Error:", error);
      return res.status(500).json({ success: false, error: error.message || "Server Error" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
